name: "Build"

on:
  push:
    branches:
      - main
      - release
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      
jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup, restore, build, test
      uses: ./.github/workflows/composite/build-restore-test.yaml

    - name: Publish signed artifact
      uses: actions/upload-artifact@v2
      with:
        name: ClassLibVersioningPlayground
        path: finalbuilt

  deployment:
   runs-on: ubuntu-latest
   needs: build
   environment:
     name: release
   steps:
     - name: Test something
       run: echo "Deployment branch"